[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:gunicorn]
command=gunicorn config.wsgi:application --bind 0.0.0.0:8006 --chdir /app
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:cron]
command=cron -f
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
